<?php

namespace AppBundle\Repository;

/**
 * NewsletterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterRepository extends \Doctrine\ORM\EntityRepository
{


    public function getNewsletters()
    {
        return $this->getEntityManager()
            ->createQuery("
                SELECT n FROM AppBundle:Newsletter n ORDER BY n.title ASC
            ")->execute();
    }

    public function getFromTopic($topic)
    {
        return $this->getEntityManager()
            ->createQuery("
                SELECT n, t
                FROM AppBundle:Newsletter n
                JOIN n.topic t
                WHERE n.topic = :topic
                ORDER BY n.title ASC
            ")
            ->setParameter("topic", $topic)
            ->execute();
    }




}
